### PR TITLE
:ambulance: fixed: fixed Iconoir v7.0.0+ update error

### PR DESCRIPTION
**Pull request by YoRolling**
- fix V7.0.0+ update error for new Icon Style
  - update README.md for new Icon Style

### CODE REVIEW

**Comment by YoRolling** [comment]
@sammarks  @mkaulfers  Hi, guys , any ideas ?

**Comment by mkaulfers** [comment]
> @sammarks @mkaulfers Hi, guys , any ideas ?

Can you specify what you're asking?

**Comment by mkaulfers** [comment]
> @sammarks @mkaulfers Hi, guys , any ideas ?

Give me just a minute to have a look at this.

**Comment by mkaulfers** [comment]
@YoRolling thanks for the contribution! I'll get a new release up ASAP.

**Comment by YoRolling** [comment]
🎉 Thank you so much.

**Pull request merged**
